name: Harvester-Node-Disk-Manager CI

# synchronize for pull request update
on:
  pull_request:
    types: [opened, reopened, synchronize]

jobs:
  build:
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: "Clone and check"
        uses: actions/checkout@v3
      - name: "Local Build for next stage"
        run: |
          BUILD_FOR_CI=true make
          ./ci/scripts/patch-ttl-repo.sh
  deploy:
    needs: build
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: "Local Deployment (Harvester+Longhorn+Node-Disk-Manager) for testing"
        run: |
          rm -rf ndm-vagrant-rancherd
          git clone https://github.com/harvester/vagrant-rancherd ndm-vagrant-rancherd
          pushd ndm-vagrant-rancherd
          ./new_cluster.sh
          yq e -i ".longhorn_version = \"1.3.2\"" settings.yaml
          ./scripts/deploy_longhorn.sh
          cp ../ci/scripts/deploy_ndm.sh ./deploy_ndm.sh
          ./deploy_ndm.sh
          popd
  tests:
    needs: deploy
    runs-on:
      - self-hosted
      - Linux
    steps:
      - name: Basic Test
        id: basic-test
        run: |
          pushd ndm-vagrant-rancherd
          ./scripts/attach-disk.sh node1
          vagrant ssh-config node1 > ../ssh-config
          cp kubeconfig ../kubeconfig
          popd
          make ci-integration
      - name: The Test failed
        if: ${{ failure() && steps.basic-test.conclusion == 'failure' }}
        run: |
          ./ci/scripts/get-ndm-log.sh
  teardown:
    needs: tests
    runs-on:
      - self-hosted
      - Linux
    if: always()
    steps:
      - name: Tear Down / Cleanup
        run: |
          pushd ndm-vagrant-rancherd
          vagrant destroy -f --parallel
          popd

