name: nightly

on:
  workflow_dispatch:
  schedule:
    # run at 03:30 UTC every night
    - cron:  '30 3 * * *'

jobs:
  build-for-dev:
    uses: ./.github/workflows/factory.yaml
    with:
      ref: v1.6
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit
