name: nightly

on:
  workflow_dispatch:
  schedule:
    # run at 03:30 UTC every night
    - cron:  '30 3 * * *'
  branches:
    - master
    - v1.6

jobs:
  build-for-dev:
    uses: ./.github/workflows/factory.yaml
    with:
      tag: ${{ github.ref_name }}-head
      push: true
    secrets: inherit